# Generated by Django 6.0.5 on 2026-05-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_id', models.CharField(help_text='ID único de la guerra en Clash', max_length=100, unique=True)),
                ('state', models.CharField(choices=[('preparation', 'Preparación'), ('inWar', 'En Guerra'), ('warEnded', 'Terminada')], max_length=20)),
                ('clan_tag', models.CharField(max_length=10)),
                ('clan_name', models.CharField(max_length=255)),
                ('opponent_tag', models.CharField(max_length=10)),
                ('opponent_name', models.CharField(max_length=255)),
                ('opponent_clan_level', models.IntegerField(default=0)),
                ('team_size', models.IntegerField()),
                ('attacks_per_member', models.IntegerField()),
                ('battle_modifier', models.CharField(default='none', help_text='none, quartermaster, etc.', max_length=50)),
                ('preparation_start_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('clan_attacks', models.IntegerField(default=0)),
                ('clan_stars', models.IntegerField(default=0)),
                ('clan_destruction_percentage', models.FloatField(default=0.0)),
                ('clan_exp_earned', models.IntegerField(default=0)),
                ('opponent_stars', models.IntegerField(default=0)),
                ('opponent_destruction_percentage', models.FloatField(default=0.0)),
                ('result', models.CharField(blank=True, choices=[('win', 'Victoria'), ('loss', 'Derrota'), ('tie', 'Empate')], help_text='Se calcula al finalizar la guerra', max_length=10, null=True)),
                ('is_league_war', models.BooleanField(default=False, help_text='¿Es una guerra de liga de guerra?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars', to='users.clan')),
            ],
            options={
                'verbose_name': 'Guerra',
                'verbose_name_plural': 'Guerras',
                'ordering': ['-end_time'],
            },
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_attacked', models.IntegerField(default=0, help_text='Cuántas veces fue atacado')),
                ('stars_received', models.IntegerField(default=0, help_text='Total de estrellas recibidas')),
                ('destruction_received', models.FloatField(default=0.0, help_text='Promedio de destrucción recibida')),
                ('successful_defenses', models.IntegerField(default=0, help_text='Ataques defendidos con éxito (0 estrellas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='players.player')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='wars.war')),
            ],
            options={
                'verbose_name': 'Defensa',
                'verbose_name_plural': 'Defensas',
            },
        ),
        migrations.CreateModel(
            name='WarParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_position', models.IntegerField(help_text='Posición en el mapa (1-50)')),
                ('town_hall_level', models.IntegerField()),
                ('attacks_used', models.IntegerField(default=0, help_text='0, 1, o 2 ataques')),
                ('total_stars', models.IntegerField(default=0)),
                ('total_destruction_percentage', models.FloatField(default=0.0)),
                ('opponent_attacks', models.IntegerField(default=0, help_text='Cuántas veces fue atacado este jugador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_participations', to='players.player')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='wars.war')),
            ],
            options={
                'verbose_name': 'Participante en Guerra',
                'verbose_name_plural': 'Participantes en Guerras',
                'ordering': ['map_position'],
            },
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_tag', models.CharField(max_length=20)),
                ('attacker_name', models.CharField(max_length=255)),
                ('defender_tag', models.CharField(max_length=20)),
                ('defender_name', models.CharField(blank=True, max_length=255)),
                ('defender_position', models.IntegerField()),
                ('stars', models.IntegerField(choices=[(0, '0 estrellas'), (1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas')])),
                ('destruction_percentage', models.FloatField()),
                ('order', models.IntegerField(help_text='Orden en el que se realizó el ataque en la guerra')),
                ('duration', models.IntegerField(help_text='Duración del ataque en segundos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='wars.war')),
                ('war_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='wars.warparticipant')),
            ],
            options={
                'verbose_name': 'Ataque',
                'verbose_name_plural': 'Ataques',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='war',
            index=models.Index(fields=['clan', '-end_time'], name='wars_war_clan_id_ba0909_idx'),
        ),
        migrations.AddIndex(
            model_name='war',
            index=models.Index(fields=['state'], name='wars_war_state_7364c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='defense',
            unique_together={('war', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='warparticipant',
            unique_together={('war', 'player')},
        ),
        migrations.AddIndex(
            model_name='attack',
            index=models.Index(fields=['war', 'order'], name='wars_attack_war_id_556079_idx'),
        ),
        migrations.AddIndex(
            model_name='attack',
            index=models.Index(fields=['attacker_tag'], name='wars_attack_attacke_0e6d45_idx'),
        ),
    ]
