# Generated by Django 6.0.5 on 2026-05-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_tag', models.CharField(help_text='Tag único del jugador en Clash (ej: #PYU89U08L)', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('coLeader', 'Co-líder'), ('leader', 'Líder'), ('member', 'Miembro')], max_length=20)),
                ('clan_rank', models.IntegerField(blank=True, help_text='Rango en el clan (1 = Líder, 2 = siguiente, etc.)', null=True)),
                ('previous_clan_rank', models.IntegerField(blank=True, null=True)),
                ('town_hall_level', models.IntegerField()),
                ('exp_level', models.IntegerField()),
                ('trophies', models.IntegerField(default=0)),
                ('builder_base_trophies', models.IntegerField(default=0)),
                ('donations', models.IntegerField(default=0)),
                ('donations_received', models.IntegerField(default=0)),
                ('league_info', models.JSONField(blank=True, default=dict, help_text="{ 'id': 29000020, 'name': 'Titan League II', 'iconUrls': {...} }")),
                ('league_tier_info', models.JSONField(blank=True, default=dict)),
                ('builder_base_league', models.JSONField(blank=True, default=dict)),
                ('player_house_elements', models.JSONField(blank=True, default=list, help_text='Elementos decorativos de la casa del jugador')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('expelled', 'Expulsado'), ('left', 'Se fue')], default='active', max_length=20)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('left_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='users.clan')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['clan_rank'],
                'indexes': [models.Index(fields=['clan', 'status'], name='players_pla_clan_id_a3b683_idx'), models.Index(fields=['clan', 'clan_rank'], name='players_pla_clan_id_506e1f_idx')],
                'unique_together': {('clan', 'player_tag')},
            },
        ),
    ]
