# Generated by Django 6.0.5 on 2026-05-16 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_tag', models.CharField(help_text='Tag único del clan en Clash (ej: #2C29G2RJL)', max_length=10, unique=True)),
                ('clan_name', models.CharField(max_length=255)),
                ('_api_token', models.CharField(db_column='api_token', max_length=500)),
                ('clan_level', models.IntegerField(default=0)),
                ('clan_points', models.IntegerField(default=0)),
                ('clan_builder_base_points', models.IntegerField(default=0)),
                ('clan_capital_points', models.IntegerField(default=0)),
                ('required_trophies', models.IntegerField(default=0)),
                ('war_frequency', models.CharField(choices=[('always', 'Siempre'), ('sometimes', 'A veces'), ('never', 'Nunca')], default='always', max_length=20)),
                ('is_war_log_public', models.BooleanField(default=True)),
                ('members_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('badge_url', models.CharField(blank=True, max_length=500)),
                ('sync_interval', models.IntegerField(choices=[(24, '24 horas'), (48, '48 horas')], default=24, help_text='Intervalo en horas para sincronizar con la API')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última sincronización exitosa', null=True)),
                ('next_sync_scheduled', models.DateTimeField(blank=True, help_text='Próxima sincronización programada', null=True)),
                ('war_wins', models.IntegerField(default=0)),
                ('war_losses', models.IntegerField(default=0)),
                ('war_ties', models.IntegerField(default=0)),
                ('war_win_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clans_administered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clan',
                'verbose_name_plural': 'Clanes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('member', 'Miembro'), ('observer', 'Observador')], default='member', max_length=20)),
                ('player_tag', models.CharField(blank=True, help_text='Tag del jugador si el usuario es miembro activo', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='users.clan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'unique_together': {('user', 'clan')},
            },
        ),
    ]
