# Generated by Django 6.0.5 on 2026-05-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='_api_token',
            field=models.TextField(db_column='api_token'),
        ),
    ]
