# Generated by Django 6.0.5 on 2026-05-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_wars', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('total_ties', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0, help_text='Porcentaje de victorias')),
                ('avg_stars_per_war', models.FloatField(default=0.0)),
                ('avg_destruction_per_war', models.FloatField(default=0.0)),
                ('active_players_this_war', models.IntegerField(default=0, help_text='Jugadores activos en la guerra actual')),
                ('avg_participation_rate', models.FloatField(default=0.0, help_text='Promedio de participación de todos')),
                ('best_attacker_tag', models.CharField(blank=True, max_length=20)),
                ('best_attacker_name', models.CharField(blank=True, max_length=255)),
                ('best_attacker_stars', models.IntegerField(default=0)),
                ('best_defender_tag', models.CharField(blank=True, max_length=20)),
                ('best_defender_name', models.CharField(blank=True, max_length=255)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clan_stats', to='users.clan')),
            ],
            options={
                'verbose_name': 'Estadística de Clan',
                'verbose_name_plural': 'Estadísticas de Clan',
            },
        ),
        migrations.CreateModel(
            name='PlayerMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_attacks', models.IntegerField(default=0)),
                ('total_stars', models.IntegerField(default=0)),
                ('avg_destruction', models.FloatField(default=0.0)),
                ('perfect_attacks', models.IntegerField(default=0)),
                ('total_donations', models.IntegerField(default=0)),
                ('total_donations_received', models.IntegerField(default=0)),
                ('trophy_change', models.IntegerField(default=0)),
                ('town_hall_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_monthly_stats', to='users.clan')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='players.player')),
            ],
            options={
                'verbose_name': 'Estadística Mensual de Jugador',
                'verbose_name_plural': 'Estadísticas Mensuales de Jugadores',
                'ordering': ['-year', '-month'],
                'unique_together': {('player', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_wars', models.IntegerField(default=0, help_text='Total de guerras en las que ha participado')),
                ('wars_participated', models.IntegerField(default=0, help_text='Guerras donde atacó al menos una vez')),
                ('war_participation_rate', models.FloatField(default=0.0, help_text='Porcentaje de participación en guerras del clan')),
                ('total_attacks', models.IntegerField(default=0)),
                ('avg_stars_per_attack', models.FloatField(default=0.0)),
                ('avg_destruction_per_attack', models.FloatField(default=0.0)),
                ('perfect_attacks', models.IntegerField(default=0, help_text='Ataques de 3 estrellas + 100% destrucción')),
                ('total_defenses', models.IntegerField(default=0)),
                ('avg_stars_lost', models.FloatField(default=0.0)),
                ('avg_destruction_suffered', models.FloatField(default=0.0)),
                ('defensive_efficiency', models.FloatField(default=0.0, help_text='Porcentaje - qué tan bien se defiende')),
                ('successful_defenses', models.IntegerField(default=0)),
                ('total_donations', models.IntegerField(default=0)),
                ('total_donations_received', models.IntegerField(default=0)),
                ('donation_balance', models.IntegerField(default=0)),
                ('current_rank', models.IntegerField(blank=True, help_text='Ranking basado en estrellas totales', null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='users.clan')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player')),
            ],
            options={
                'verbose_name': 'Estadística de Jugador',
                'verbose_name_plural': 'Estadísticas de Jugadores',
                'indexes': [models.Index(fields=['clan', '-total_attacks'], name='stats_playe_clan_id_a0787a_idx'), models.Index(fields=['clan', '-current_rank'], name='stats_playe_clan_id_1bf54b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_date', models.DateField(help_text='Fecha de la guerra')),
                ('total_wars_this_period', models.IntegerField(default=0, help_text='Total de guerras en este período')),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('total_ties', models.IntegerField(default=0)),
                ('avg_stars', models.FloatField(default=0.0, help_text='Promedio de estrellas obtenidas')),
                ('avg_destruction', models.FloatField(default=0.0, help_text='Promedio de destrucción lograda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_logs', to='users.clan')),
            ],
            options={
                'verbose_name': 'Registro de Guerra',
                'verbose_name_plural': 'Registros de Guerras',
                'ordering': ['-war_date'],
                'unique_together': {('clan', 'war_date')},
            },
        ),
    ]
